### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by ghost** [Decentr-net/browser-andoroid#1]
### Steps to reproduce

1. There is a problem when I download a video file. The download will last for a minute (approximately), then after that it disappears from the download and then after a period of time comes back

2. The reward system is not sending data to the blockchain in my case if I download (Android app) "PVD in progress" does not decrease

### Expected behaviour

A

### Actual behaviour

B

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

87.2.0

### Device logs

ffd42c73-b47a-46ea-8e19-cff4483cf07f
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.decentr.browser/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity}: kotlin.UninitializedPropertyAccessException: lateinit property viewModelFactory has not been initialized
----
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.decentr.browser/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity}: kotlin.UninitializedPropertyAccessException: lateinit property viewModelFactory has not been initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4031)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property viewModelFactory has not been initialized
	at org.mozilla.fenix.HomeActivity$onCreate$1.invoke(HomeActivity.kt:25)
	at org.mozilla.fenix.perf.StrictModeManager.resetAfter$instrumentedFunctionBlock(StrictModeManager.kt:2)
	at org.mozilla.fenix.perf.StrictModeManager.resetAfter(StrictModeManager.kt:7)
	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:11)
	at android.app.Activity.performCreate(Activity.java:8282)
	at android.app.Activity.performCreate(Activity.java:8262)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
	... 12 more

**Comment by alexeypalto** [comment]
Fixed with update
